# Generated by Django 3.0.7 on 2020-06-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.CharField(default='img', max_length=255),
            preserve_default=False,
        ),
    ]
