# Generated by Django 3.0.7 on 2020-06-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1app', '0002_gift_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='gift',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.TextField(),
        ),
    ]
